version: '3.7'

services:
  frontend:
    image: ahitcher/1r-hackathon-2021:latest
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.services.frontend.loadbalancer.server.port=9000
      - traefik.http.routers.frontend.entrypoints=https
      - traefik.http.routers.frontend.rule=Host(`www.onerecord.fr`)

networks:
  traefik:
    external: true
    name: onerecord-traefik