name: Build, test and deploy
on:
  push:
    paths-ignore:
      - "*.md"
env:
  DOCKER_REPOSITORY: ahiltcher/1r-hackathon-2021
  CI: false

jobs:
  build:
    name: Build, test, Docker artifact and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: CI=false npm run build

      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          tag_with_ref: true
          add_git_labels: true

      - name: Deploy app
        run: |
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          docker-compose -H "ssh://${{ secrets.USER }}@${{ secrets.HOST }}" up -d
